version: '3'

services:
  client:
    image: nginx
    restart: unless-stopped
    container_name: nginx-default
    ports:
        - 80
    volumes:
        - ./src:/usr/share/nginx/html
    networks:
      local_br:
        ipv4_address: 192.168.99.101

networks:
  local_br:
    name: br0
    driver: bridge
