
version: '2'
services:
  odoo:
    image: odoo:latest
    ports:
      - "8069:8069"
    env_file:
      - .env
    environment:
      - ODOO_HOST=odoo_db
      - ODOO_USER=odoo
      - ODOO_PASSWORD=myodoo
    networks:
      - local_br
  odoo_db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - local_br
networks:
  local_br:
    name: br0
    driver: bridge