version: '3'

services:
  node-red:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    restart: always
    networks:
      - local_br

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto-data:/mosquitto/data
      - ./mosquitto-config:/mosquitto/config
    restart: always
    networks:
      - local_br
      

networks:
  local_br:
    name: br0
    driver: bridge