version: '3'

services:

  mysql57:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql57
    env_file:
      - .env
    ports:
      - 3306
    volumes:
      - ./mysql57:/var/lib/mysql
    networks:
      - local_br

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    # links:
    #   - db
    environment:
      PMA_HOST: mysql57
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      - local_br
    ports:
      - 80

networks:
  local_br:
    name: br0
    driver: bridge
