version: '3.7'
services:
  mailserver:
    container_name: mailserver
    image: analogic/poste.io
    ports:
      - "8080:80"
      - "8443:443"
      - "143:143"
      - "25:25"
      - "110:110"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/htmlnginx/html/.well-known:/opt/www/.well-known
      - ./data:/data
    networks:
      - local_br
networks:
  local_br:
    name: br0
    driver: bridge
    external: true